os: linux
dist: xenial
language: python
python:
- '3.8'

cache:
  directories:
  - ".pip_download_cache"

env:
  jobs:
  - REQUESTS="-U requests"
  global:
  - PIP_DOWNLOAD_CACHE=".pip_download_cache"

jobs:
  allow_failures:
  - env: REQUESTS="-e git+git://github.com/requests/requests.git#egg=requests"
  - python: nightly

install:
- pip install codecov
- pip install ${REQUESTS}
- make install-deps

script:
- make
- pytest . --cov-report term-missing  --cov . --cov-report="xml:.artifacts/coverage.xml"
  --junit-xml=".artifacts/junit.xml"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  username:
    secure: Mt6mQiqtcxi1xf3TpTtPQ5fJ97LQiO754qV1zsK2izTs5kDg5NhJUUGReJCKvl9fJKbGqGwT+RR1q6/5kW1s8UGVduqLfBUBUSW++qciwcvIg2B3DlBFuW7vVfzi0DCF6xssjSjwpXH4iAg5QO71qOkoE9t71G2boKxUuK1wL+E=
  password:
    secure: SejRAkh567ae8HNgLMWebpPwOxn2+wfrKWHkm8JTmCJcxKIQmfbPlUJPAspJ9HF7kBB1MzkkqNkXG184VEgH1l1JqUNyZKqrk+y4R3s+jjJ+Yqepm3SeAiq5FceS8BwCegO9L3po299NtdWFHllydVLLL+Rf3ZnCQOl5YT1tzzk=
  on:
    tags: true
